/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function Moon(props) {
  const { nodes, materials } = useGLTF("./moon.gltf");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={100}
        near={0.1}
        fov={22.9}
        position={[1.88, 0.81, 0.68]}
        rotation={[1.51, 0.71, -1.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[0, 1.29, 0]}
        rotation={[Math.PI, -0.03, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("./moon.gltf");
